name: Release GitHub

on:
  push:
    branches: [release/*]

jobs:
  create-github-release:
    name: Create GitHub Release and Git tag
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: cucumber/action-create-github-release@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
